---
root: true
extends:
  - standard
  - prettier
  - prettier/standard
  - plugin:jest/recommended
plugins:
  - standard
  - prettier
rules:
  prettier/prettier: error
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 8
  sourceType: script
