language: node_js
node_js:
  - 8
before_install:
  - npm install -g npm@5 greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run ci-test
after_script:
  - greenkeeper-lockfile-upload
env:
  global:
    secure: Z/MabBFG4JXsmpbXA02k+WVsvPyx2fGn8clouFGgnTnRtcTVFCdQuVR90LlUvFDxcsPAdhZchlimwe1EEcgksl0PohN4P+NoHQYW/nIthB9La81eht9K/xsiMJ+w5KAfJJvW1WPAITGUG9YOEBUYRMrqYG8CYJKmAdXKCXb7cKo=
