language: node_js
node_js:
  - 8
before_install:
  - npm install -g npm@6 greenkeeper-lockfile
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run ci-test
after_script:
  - greenkeeper-lockfile-upload
before_deploy:
  - npm install -g now
deploy:
  - provider: script
    script: bin/deploy.sh
    on:
      all_branches: false
      branch: master
env:
  global:
    - secure: Z/MabBFG4JXsmpbXA02k+WVsvPyx2fGn8clouFGgnTnRtcTVFCdQuVR90LlUvFDxcsPAdhZchlimwe1EEcgksl0PohN4P+NoHQYW/nIthB9La81eht9K/xsiMJ+w5KAfJJvW1WPAITGUG9YOEBUYRMrqYG8CYJKmAdXKCXb7cKo=
    - secure: L1070jck+L2BSZ3/X+OfR6Lf4HGWBlNgRUr3H8/Fyb33a6uHVuHdSlTv5kB3KKc5iFmLb/IPx+SA2XygWg1AaAHPGBbgWJn7yhmXW3v6d6J7cfLPwoKRMsJdj2ssz8sf7qdg3fF9Eg/tRUtMvDW7vZM1PYLJFRAt2lcYsNBLvJk=
